$(function(){
	if(localStorage.getItem('user')){
		$('#userBox').html('你好,'+localStorage.getItem('user'));
		$("#zhu").html('注销');
	}
	$('#userBox').click(function(e){
		if(localStorage.getItem('user')){
			e.preventDefault();
		}
	})
	$("#ckdd").click(function(e){
		e.preventDefault();
		location.href="../hu/我的订单.html"
	})
	$("#fhzf").click(function(e){
		e.preventDefault();
		location.href="支付.html"
	})
})
