$(function(){
	if(localStorage.getItem('user')){
		$('#userBox').html('你好,'+localStorage.getItem('user'));
		$("#zhu").html('注销');
	}
	$('#userBox').click(function(e){
		if(localStorage.getItem('user')){
			e.preventDefault();
		}
	})
	$(".btn").click(function(){
		if($('.inp').val()==0000){
			location.href="支付成功.html"
		}else{
			location.href="支付失败.html"
		}
	})
})
